import { configure } from '@kadira/storybook';

// required npm dependency
import 'react-mdl/extra/material.css';
import 'react-mdl/extra/material';

// either run stories with generated "dist" or "src". comment the alternative
// TODO: separate storybook config?

// "lib" - make sure stuff generated by webpack works
// import '../lib/mdl-ui';

// "src" - fast development feedback
import '../src/index';
import '../src/assets/material-icons.css'
import '../src/assets/roboto/roboto.css';

function loadStories() {
  require('../src/.stories'); // eslint-disable-line global-require
}

configure(loadStories, module);
